input_channel: 3

depth_multiple: 1.0
width_multiple: 1.0

backbone:
    # [repeat, module, args]
    [
        # Conv argument: [out_channel, kernel_size, stride, padding_size]
        # if padding_size is not given or null, the padding_size will be auto adjusted as padding='SAME' in TensorFlow
        [1, Conv, [16, 3, 2, null, 1, "HardSwish"]],
        # k t c SE HS s
        [1, InvertedResidualv3, [3, 1, 16, 1, 0, 2]],
        [1, InvertedResidualv3, [3, 4.5, 24, 0, 0, 2]], # 2-P2/4, 24 # stride 1 for cifar, 2 for others
        [1, InvertedResidualv3, [3, 3.67, 24, 0, 0, 1]],
        [1, InvertedResidualv3, [5, 4, 32, 1, 1, 2]], # 4-P3/8, 40
        [1, InvertedResidualv3, [5, 6, 32, 1, 1, 1]],
        [1, InvertedResidualv3, [5, 3, 40, 1, 1, 1]], # 7-P4/16, 80
        [1, InvertedResidualv3, [5, 6, 72, 1, 1, 2]],
        [1, InvertedResidualv3, [5, 6, 72, 1, 1, 1]],
        [1, Conv, [432, 1, 1]],
        [1, GlobalAvgPool, []],
        [1, Conv, [1024, 1, 1]],
        [1, Flatten, []],
        [1, Linear, [9]]
    ]