#스퀴즈넷에 꽂혀서 이것만 팠습니다. 성능은 알렉스넷인데 파라미터 수를 대폭 줄인 모델이라는 걸 알고는
#이걸 파야겠다고 결심했어요. macs가 그리 낮은 것도 아닌데 f1-score는 0.2~0.3정도로밖에 안오르고
#학습 시간도 한 에폭 당 2분 후반대 정도로 다른 모델과 비슷해서
#정말 슬픕니다.

#중간 중간에 끼어있는 Fire와 MaxPool을 주석처리 해보았는데도 macs는 별로 떨어지지 않는데
#마지막 FixedConv인가 Linear인가를 주석처리 하니까 macs가 확 떨어지면서 f1-score는 거의 0에 수렴했습니다.
#차라리 빨리 셔플넷으로 할 걸... 리더보드 높으신 다른 분들도 다 셔플넷으로 하시더라구요...
#사실 셔플넷 구조가 너무 복잡해보여서 안 건드리려 하기도 했지만...

input_channel: 3

depth_multiple: 1.0
width_multiple: 0.2

backbone:
    [
        [1, Conv, [96, 7, 2, [0]]],
        [1, MaxPool, [2]],
        [1, Fire, [16, 64, 64]],
        #[1, Fire, [16, 64, 64]],
        [1, Fire, [32, 128, 128]],
        #[1, MaxPool, [2]],
        #[1, Fire, [32, 128, 128]],
        #[1, Fire, [48, 192, 192]],
        #[1, Fire, [48, 192, 192]],
        #[1, Fire, [64, 256, 256]],
        #[1, MaxPool, [2]],
        #[1, Fire, [64, 256, 256]],
        [1, Dropout, [0.5]],
        [1, FixedConv, [9, 1, 1]],
        [1, GlobalAvgPool, []],
        [1, Flatten, []],
        [1, Linear, [9]]
    ]