wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.30
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 2
      4: 3.8.5
      5: 0.10.30
      8:
      - 5
batch_size:
  desc: null
  value: 16
img_size:
  desc: null
  value: 1
init_lr:
  desc: null
  value: 0.0002783543525364507
